export const GET_LOGIN_ERRORS = "GET_LOGIN_ERRORS";
export const GET_REGISTER_ERRORS = "GET_REGISTER_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const NEW_USER_REGISTERED = "NEW_USER_REGISTERED";
export const GET_PROJECT_DATA = "GET_PROJECT_DATA";
